//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChromiumCcsipro.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebChromiumCcsipro.Resources.Language.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswodWindowTitle {
            get {
                return ResourceManager.GetString("ChangePasswodWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ChangePasswordWindowCancelButton {
            get {
                return ResourceManager.GetString("ChangePasswordWindowCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordWindowChangeButton {
            get {
                return ResourceManager.GetString("ChangePasswordWindowChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password doesnt match !.
        /// </summary>
        public static string ChangePasswordWindowChangeButtonTooltip {
            get {
                return ResourceManager.GetString("ChangePasswordWindowChangeButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        public static string ChangePasswordWindowFirstPasswordTextBox {
            get {
                return ResourceManager.GetString("ChangePasswordWindowFirstPasswordTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cant be empty or shorted than 5 character !.
        /// </summary>
        public static string ChangePasswordWindowPasswordBoxTooltip {
            get {
                return ResourceManager.GetString("ChangePasswordWindowPasswordBoxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Again password:.
        /// </summary>
        public static string ChangePasswordWindowSecondPasswordTextBox {
            get {
                return ResourceManager.GetString("ChangePasswordWindowSecondPasswordTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string EnterSettingWindowEnterButton {
            get {
                return ResourceManager.GetString("EnterSettingWindowEnterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string EnterSettingWindowTextBlock {
            get {
                return ResourceManager.GetString("EnterSettingWindowTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string EnterSettingWindowTitle {
            get {
                return ResourceManager.GetString("EnterSettingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please restart the application.
        ///{0}.
        /// </summary>
        public static string ErrorMessageFormat {
            get {
                return ResourceManager.GetString("ErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCSIpro Chromium.
        /// </summary>
        public static string SettingButtonApplication {
            get {
                return ResourceManager.GetString("SettingButtonApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change settings password.
        /// </summary>
        public static string SettingButtonChangePassword {
            get {
                return ResourceManager.GetString("SettingButtonChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOZP Signature.
        /// </summary>
        public static string SettingButtonSignature {
            get {
                return ResourceManager.GetString("SettingButtonSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingWindowsTitle {
            get {
                return ResourceManager.GetString("SettingWindowsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click for signature.
        /// </summary>
        public static string TrayIconToolTipDefault {
            get {
                return ResourceManager.GetString("TrayIconToolTipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
    }
}
